[build]
  # Команда для сборки проекта
  command = "npm run build"
  
  # Папка с результатом сборки
  publish = "dist"
  
  # Переменные окружения для сборки
  [build.environment]
    NODE_VERSION = "18"
    # Supabase Configuration
    VITE_SUPABASE_URL = "https://xajclkhhskkrgqwzhlnz.supabase.co"
    VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhamNsa2hoc2trcmdxd3pobG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzIwNDYsImV4cCI6MjA2MzY0ODA0Nn0.K76opG9RFtM8iQQaQxDBIYgbiTmM61Hp8fGgA-Q2i9o"
    VITE_DEBUG_MODE = "false"
    # Telegram Bot Configuration (замените на имя вашего реального бота)
    VITE_TELEGRAM_BOT_USERNAME = "FiestaEventBot"

# Настройки редиректов для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Настройки заголовков безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Настройки для статических файлов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 